default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: NovaSenha123!
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: notification_microservice_development

test:
  <<: *default
  database: notification_microservice_test

production:
  <<: *default
  database: notification_microservice_production
  username: notification_microservice
  password: <%= ENV["NOTIFICATION_MICROSERVICE_DATABASE_PASSWORD"] %>
